name: module_rongcloud_im
description: RongCloud IM infrastructure for flutter_module_sample.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  uuid: ^4.5.1
  rongcloud_im_wrapper_plugin: ^5.44.0
  module_common_ui:
    path: ../../commons/ui
  module_core:
    path: ../../commons/core
  module_http:
    path: ../../commons/network
  module_global_cache:
    path: ../../commons/storage
  wys_router:
    path: ../../commons/wys_router
  module_utils:
    path: ../../commons/toolkit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# 与根工程一致：消解 module_utils 内 rxdart 冲突。
dependency_overrides:
  rxdart: ^0.27.7

flutter:
