name: module_utils
description: Common utilities for flutter_module_sample.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^12.4.0
  flutter_html: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  logger: ^2.7.0
  lottie: ^3.3.3
  path_provider: ^2.1.5
  rx_event_bus: ^2.0.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  rxdart: ^0.27.7

flutter:
