name: module_classroom
description: Classroom teaching module (UI POC with mock data).
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  module_common_ui:
    path: ../../commons/ui
  module_core:
    path: ../../commons/core
  module_route:
    path: ../../route

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
