name: module_linking
description: Deeplink + JPush linking infrastructure for flutter_module_sample.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  module_common_ui:
    path: ../../commons/ui
  module_core:
    path: ../../commons/core
  wys_router:
    path: ../../commons/wys_router
  module_utils:
    path: ../../commons/toolkit
  module_global_cache:
    path: ../../commons/storage
  module_http:
    path: ../../commons/network
  wys_push:
    path: ../wys_push

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
