name: module_rongcloud_im
description: RongCloud IM infrastructure for flutter_module_sample.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  uuid: ^4.5.1
  module_auth:
    path: ../../features/auth
  module_common_ui:
    path: ../../commons/ui
  module_core:
    path: ../../commons/core
  module_global_cache:
    path: ../../commons/storage
  module_route:
    path: ../../route
  module_utils:
    path: ../../commons/toolkit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
