name: module_settings
description: Settings module for flutter_module_sample.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  module_common_ui:
    path: ../../commons/ui
  module_core:
    path: ../../commons/core
  module_http:
    path: ../../commons/network
  module_route:
    path: ../../route
  module_utils:
    path: ../../commons/toolkit
  module_linking:
    path: ../../infrastructure/linking
  module_realtime:
    path: ../../infrastructure/realtime
  module_rongcloud_im:
    path: ../../infrastructure/rongcloud_im
  module_bluetooth:
    path: ../../infrastructure/bluetooth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
