name: module_chat
description: Chat module.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  image_picker: ^1.1.2
  module_common_ui:
    path: ../../ui
  module_core:
    path: ../../core
  module_route:
    path: ../../route
  module_utils:
    path: ../../toolkit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
