name: module_friend
description: Friend module.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  module_common_ui:
    path: ../../commons/ui
  module_route:
    path: ../../packages/route
  module_utils:
    path: ../../commons/toolkit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
